// <auto-generated />
namespace GeneralStore.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initMar23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initMar23));
        
        string IMigrationMetadata.Id
        {
            get { return "202103232000080_initMar23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
